Allow optional symbol for SwiftUI's `Label`
SFSafeSymbols/SFSafeSymbols pull request #119
Opened 2023-01-27 17:50 UTC by StevenSorial

When using SwiftUI, i find myself writing `Label("My Label", systemImage: showImage ? "plus" : "")`, which doesn't translate well when using `SFSafeSymbols`.
Option 1:
```
If showImage {
	Label("My Label", systemSymbol: .plus)
} else {
	Text("My Label")
}
```

Options 2:
```
Label("My Label", systemSymbol: showImage ? .plus : .init(rawValue: ""))
```

Option 3:
```
Label("My Label", systemSymbol: .plus)
	.labelStyle(showImage ? .titleAndIcon : .titleOnly)
```
I think option 1 is too verbose, option 2 requires the user to understand how the SFSymbol initializers work, option 3 I think Is the most acceptable but I think it's a little weird to always assign an image.

This PR makes the symbol optional to be:

```
Label("My Label", systemSymbol: showImage ? .plus : nil)
```

2023-01-27 22:38 UTC, fredpi requested changes
@StevenSorial Thanks, LGTM!

Just two small details:

- Could you add a changelog entry?
- Could you document the behavior when a `nil` value is passed (in the documentation of the function)?

2023-01-27 23:01 UTC, fredpi approved these changes

2023-01-27 23:48 UTC, merged

2023-01-28 17:27 UTC, StevenSorial commented
@fredpi  Do you mind if we released 4.1.1 with this change?

2023-01-30 23:42 UTC, fredpi commented
@StevenSorial That'd be good 👍 Feel free to do the release :)