Swift 6 consideration: make SFSymbol Sendable
SFSafeSymbols/SFSafeSymbols pull request #128
Opened 2024-02-06 22:30 UTC by Dean151

## Motivation
Swift 6 is coming (one day?) and Strict Concurrency Checking is the new safe default to build new projects.
Since latest Xcode beta (15.3 beta 2), Strict Concurrency warnings are becoming more powerful … and trigger warnings on SFSymbols and related not being sendable.

## An easy fix
Therefore, the fix is easy. A class is sendable when it's immutable and not overridable, or when it manage its internal state safely. In our case, we don't have the "not overridable", but it's manageable! The class only store immutable data (rawValue) and it's not overridable outside of the module, because it's not open. Therefore, we can safely assume it's Sendable by default, and add `@unchecked Sendable`.
Unchecked is a little bit misnamed, maybe? It's not that we haven't checked as a developer. It means the compiler hadn't checked it. 
And like we say. With great power comes great responsibility.

2024-02-17 05:44 UTC, StevenSorial commented
Thanks for the PR. can you please rebase before I can take a look?

2024-02-17 10:00 UTC, Dean151 commented
Hi @StevenSorial !
The rebase is complete !
Have a nice review :)

2024-02-17 12:50 UTC, StevenSorial commented
Thanks. I left one comment.
Could you also please add a changelog entry with that change?

2024-02-17 17:09 UTC, Dean151 commented
@StevenSorial I can't see your comment yet, is it still "pending for sending" in the review feature of Github?

2024-02-17 20:47 UTC, StevenSorial requested changes

2024-02-17 20:47 UTC, StevenSorial commented on Sources/SFSafeSymbols/Symbols/SymbolLocalizations.swift
> +public enum Localization: String, Equatable, Sendable {
Correct me if I'm wrong, but I don't think simple enums need an explicit conformance.
if that's the case then we can remove it

2024-02-18 16:55 UTC, Dean151 commented on Sources/SFSafeSymbols/Symbols/SymbolLocalizations.swift
> +public enum Localization: String, Equatable, Sendable {
I agree. Since String is Sendable, so is the enum, implicitly. Removing it right away!

2024-02-18 17:04 UTC, Dean151 commented on Sources/SFSafeSymbols/Symbols/SymbolLocalizations.swift
> +public enum Localization: String, Equatable, Sendable {
And it's done :)

2024-02-18 19:19 UTC, StevenSorial commented
Thanks for the changes. Feel free to credit yourself in the changelog using the same format as the rest.
I will merge the PR tomorrow.

2024-02-20 06:50 UTC, merged